---
services:
  docker-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: docker-proxy
    environment:
      - CONTAINERS=1
      - IMAGES=1
      - NETWORKS=1
      - VOLUMES=1
      - POST=1
      - AUTH=1
      - INFO=1
      - EVENTS=1
      - PORT=1
    networks: [docker-proxy-net]
    privileged: true
    volumes: [/var/run/docker.sock:/var/run/docker.sock:ro]
  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    user: 1000:1000
    volumes: [./data/dockhand:/app/data]
    networks: [docker-proxy-net]
    ports: [1000:3000]
networks:
  docker-proxy-net:
    name: docker-proxy-net
  lefrigo-net:
    driver: bridge
    name: lefrigo-net
