---
services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver-preprod
    restart: unless-stopped
    ports: [8978:8978]
    volumes: ['${APPS_DATA_DIR}/cloudbeaver:/opt/cloudbeaver/workspace']
    networks: [lefrigo-net, jellystat-net]
    labels:
      - traefik.enable=true
      - traefik.http.routers.cloudbeaver.rule=Host(`dbeaver.le-frigo.fr`)
      - traefik.http.routers.cloudbeaver.entrypoints=websecure
      - traefik.http.routers.cloudbeaver.tls=true
      - traefik.http.routers.cloudbeaver.tls.certresolver=myresolver
      - traefik.http.routers.cloudbeaver.service=cloudbeaver-svc
      - traefik.http.services.cloudbeaver-svc.loadbalancer.server.port=8978
      - traefik.http.routers.cloudbeaver.middlewares=tinyauth-middleware@docker,error-pages-middleware@docker
      - tinyauth.apps.cloudbeaver.ldap.groups=admin
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: [CMD, curl, -f, http://localhost:8978/]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  jellystat-db:
    image: postgres:18.1
    shm_size: 1gb
    container_name: jellystat-db
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: '5'
        max-size: 10m
    environment:
      POSTGRES_USER: ${JELLYSTAT_DB_USER}
      POSTGRES_PASSWORD: ${JELLYSTAT_DB_PASSWORD}
    volumes: ['${APPS_DATA_DIR}/jellystat-db:/var/lib/postgresql']
    healthcheck:
      test: [CMD-SHELL, pg_isready --dbname=postgres --username=postgres]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [jellystat-net]
  jellystat:
    image: cyfershepard/jellystat:latest
    container_name: jellystat
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: '5'
        max-size: 10m
    environment:
      POSTGRES_USER: ${JELLYSTAT_DB_USER}
      POSTGRES_PASSWORD: ${JELLYSTAT_DB_PASSWORD}
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: ${JELLYSTAT_JWT_SECRET}
      TZ: Europe/Paris
    volumes: ['${APPS_DATA_DIR}/jellystat:/app/backend/backup-data']
    ports: [3435:3000]
    networks: [lefrigo-net, jellystat-net]
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellystat.rule=Host(`jellystat.le-frigo.fr`)
      - traefik.http.routers.jellystat.entrypoints=websecure
      - traefik.http.routers.jellystat.tls=true
      - traefik.http.routers.jellystat.tls.certresolver=myresolver
      - traefik.http.routers.jellystat.service=jellystat-svc
      - traefik.http.services.jellystat-svc.loadbalancer.server.port=3000
      - traefik.http.routers.jellystat.middlewares=tinyauth-middleware@docker,error-pages-middleware@docker
      - tinyauth.apps.jellystat.ldap.groups=admin
    depends_on:
      jellystat-db:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/auth/isConfigured
        || exit 1
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 30s
  beszel:
    image: henrygd/beszel
    container_name: beszel
    restart: unless-stopped
    environment:
      - APP_URL=https://monitoring.le-frigo.fr
    ports:
      - 8090:8090
    volumes:
      - ${APPS_DATA_DIR}/beszel/hub:/beszel_data
    labels:
      - traefik.enable=true
      - traefik.http.routers.beszel.rule=Host(`monitoring.le-frigo.fr`)
      - traefik.http.routers.beszel.entrypoints=websecure
      - traefik.http.routers.beszel.tls=true
      - traefik.http.routers.beszel.tls.certresolver=myresolver
      - traefik.http.routers.beszel.service=beszel-svc
      - traefik.http.services.beszel-svc.loadbalancer.server.port=8090
      - traefik.http.routers.beszel.middlewares=tinyauth-middleware@docker,error-pages-middleware@docker
      - tinyauth.apps.beszel.ldap.groups=admin
    networks: [lefrigo-net]
    healthcheck:
      test: ['CMD', '/beszel', 'health', '--url', 'http://localhost:8090']
      interval: 120s
      start_period: 10s
      timeout: 5s
  beszel-agent:
    image: henrygd/beszel-agent
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    devices:
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
      - /dev/sdc:/dev/sdc
      - /dev/nvme0n1:/dev/nvme0n1
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${APPS_DATA_DIR}/beszel/agent:/var/lib/beszel-agent
    environment:
      LISTEN: 45876
      KEY: ${BESZEL_AGENT_KEY}
      TOKEN: ${BESZEL_AGENT_TOKEN}
      HUB_URL: https://monitoring.le-frigo.fr
      FILESYSTEM: /dev/nvme0n1
      STOCKAGE_DISK: /dev/sda
      APPS_DISK: /dev/nvme0n1
    healthcheck:
      test: ['CMD', '/agent', 'health']
      interval: 120s
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - dozzle_data:/data
    environment:
      - DOZZLE_ENABLE_ACTIONS=true
      - DOZZLE_ENABLE_SHELL=true
      - DOZZLE_HOSTNAME=le-frigo.fr
      - DOZZLE_REMOTE_AGENT=dozzle-agent:7007
    labels:
      - traefik.enable=true
      - traefik.http.routers.dozzle.rule=Host(`dozzle.le-frigo.fr`)
      - traefik.http.routers.dozzle.entrypoints=websecure
      - traefik.http.routers.dozzle.tls=true
      - traefik.http.routers.dozzle.tls.certresolver=myresolver
      - traefik.http.routers.dozzle.service=dozzle-svc
      - traefik.http.services.dozzle-svc.loadbalancer.server.port=8080
      - traefik.http.routers.dozzle.middlewares=tinyauth-middleware@docker,error-pages-middleware@docker
      - tinyauth.apps.dozzle.ldap.groups=admin
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks: [lefrigo-net]
  dozzle-agent:
    image: amir20/dozzle:latest
    container_name: dozzle-agent
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7007:7007
    networks: [lefrigo-net]
  borgui:
      image: ainullcode/borg-ui:latest
      container_name: borg-web-ui
      restart: unless-stopped
      volumes:
        - ${APPS_DATA_DIR}/borg/data:/data
        - ${APPS_DATA_DIR}/borg/cache:/home/borg/.cache/borg
        - /etc/localtime:/etc/localtime:ro
        - /home/truenas_admin:/local:rw
        - ${APPS_DATA_DIR}:/containers
        - ${MEDIA_DATA_DIR}:/media
      environment:
        - PORT=${PORT:-8081}
        - PUID=${PUID:-1001}
        - PGID=${PGID:-1001}
        - TZ=Europe/Paris
        - LOCAL_MOUNT_POINTS=${LOCAL_MOUNT_POINTS:-/local}
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - REDIS_DB=0
      depends_on:
        redis:
          condition: service_healthy
      labels:
        - traefik.enable=true
        - traefik.http.routers.borgui.rule=Host(`backup.le-frigo.fr`)
        - traefik.http.routers.borgui.entrypoints=websecure
        - traefik.http.routers.borgui.tls=true
        - traefik.http.routers.borgui.tls.certresolver=myresolver
        - traefik.http.routers.borgui.service=borg-svc
        - traefik.http.services.borg-svc.loadbalancer.server.port=8081
        - traefik.http.routers.borgui.middlewares=tinyauth-middleware@docker,error-pages-middleware@docker
        - tinyauth.apps.borgui.ldap.groups=admin
      networks: [lefrigo-net]
  redis:
    image: redis:7-alpine
    container_name: borg-redis
    restart: unless-stopped
    command: >
      redis-server
      --maxmemory 2gb
      --maxmemory-policy allkeys-lru
      --save ""
      --appendonly no
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
volumes:
  dozzle_data:
networks:
  lefrigo-net:
    external: true
  jellystat-net:
