services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ${APPS_DATA_DIR}/ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    networks:
      - lefrigo-net

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    ports:
      - "5111:8080"
    volumes:
      - ${APPS_DATA_DIR}/open-webui:/app/backend/data
    networks:
      - lefrigo-net
    depends_on:
      - ollama
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
      WEBUI_SECRET_KEY: ${WEBUI_SECRET_KEY}
      WEBUI_AUTH_TRUSTED_EMAIL_HEADER: X-authentik-email
      WEBUI_AUTH_TRUSTED_NAME_HEADER: X-authentik-name
      ENABLE_SIGNUP: "True"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ia.rule=Host(`ia.le-frigo.fr`)"
      - "traefik.http.routers.ia.service=ia"
      - "traefik.http.routers.ia.entrypoints=websecure"
      - "traefik.http.routers.ia.tls.certresolver=myresolver"
      - "traefik.http.routers.ia.middlewares=authentik@docker"
      - "traefik.http.services.ia.loadbalancer.server.port=8080"

networks:
  lefrigo-net:
    external: true