services:
  # --- COMMON DATABASE ---
  postgres-common:
    image: postgres:16-alpine
    container_name: postgres-common
    restart: always
    user: "${PUID}:${PGID}"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_MULTIPLE_DATABASES: authentik,outline
    volumes:
      - ${APPS_DATA_DIR}/postgre/data:/var/lib/postgresql/data
      - ${FOLDER_PATH}/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    networks:
      - lefrigo-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 1024M
  
  # --- DOCKER PROXY FOR APPLICATIONS ---
  docker-proxy-read:
    container_name: docker-proxy-read
    environment:
      - CONTAINERS=1
      - NETWORKS=1
      - EVENTS=1
      - VERSION=1
      - IMAGES=1
      - INFO=1
      - PING=1
    image: tecnativa/docker-socket-proxy
    networks:
      - lefrigo-net
    privileged: True
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  # --- REVERSE PROXY ---
  traefik:
    image: traefik:v3.6.9
    container_name: traefik
    user: "${PUID}:${PGID}"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - lefrigo-net
    ports:
      - 81:80
      - 444:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APPS_DATA_DIR}/traefik/acme.json:/acme.json
    command:
      - --ping=true
      - --api.insecure=true
      - --api.dashboard=true
      - --log.level=INFO
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.endpoint=tcp://docker-proxy-read:2375
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --certificatesresolvers.myresolver.acme.httpchallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.myresolver.acme.storage=/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.le-frigo.fr`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=myresolver"
      - "traefik.http.routers.dashboard.middlewares=authentik@docker"
    depends_on:
      error-pages:
        condition: service_healthy
  
  # --- REDIS ---
  redis:
    image: redis:7-alpine
    container_name: common-redis
    restart: always
    networks:
      - lefrigo-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 3

  # --- AUTHENTIK SERVER ---
  authentik-server:
    image: ghcr.io/goauthentik/server:2025.12.4
    container_name: authentik-server
    user: "${PUID}:${PGID}"
    command: server
    restart: unless-stopped
    depends_on:
      postgres-common:
        condition: service_healthy
    environment:
      - AUTHENTIK_POSTGRESQL__HOST=postgres-common
      - AUTHENTIK_POSTGRESQL__USER=${POSTGRES_USER}
      - AUTHENTIK_POSTGRESQL__NAME=authentik
      - AUTHENTIK_POSTGRESQL__PASSWORD=${POSTGRES_PASSWORD}
      - AUTHENTIK_ERROR_REPORTING__ENABLED=true
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY}
      - AUTHENTIK_EMAIL__HOST=${AUTHENTIK_EMAIL__HOST}
      - AUTHENTIK_EMAIL__PORT=${AUTHENTIK_EMAIL__PORT}
      - AUTHENTIK_EMAIL__USERNAME=${AUTHENTIK_EMAIL__USERNAME}
      - AUTHENTIK_EMAIL__PASSWORD=${AUTHENTIK_EMAIL__PASSWORD}
      - AUTHENTIK_EMAIL__USE_SSL=${AUTHENTIK_EMAIL__USE_SSL}
      - AUTHENTIK_EMAIL__FROM=${AUTHENTIK_EMAIL__FROM}
    ports:
      - 9000:9000
      - 9443:9443
    volumes:
      - ${APPS_DATA_DIR}/authentik/data:/data
      - ${APPS_DATA_DIR}/authentik/media:/media
      - ${APPS_DATA_DIR}/authentik/custom-templates:/templates
      - ${APPS_DATA_DIR}/authentik/geoip:/geoip
      - ${APPS_DATA_DIR}/authentik/custom-icons:/web/dist/assets/icons
    networks:
      - lefrigo-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authentik.rule=Host(`auth.le-frigo.fr`)"
      - "traefik.http.routers.authentik.entrypoints=websecure"
      - "traefik.http.routers.authentik.tls.certresolver=myresolver"
      - "traefik.http.middlewares.authentik.forwardauth.maxResponseBodySize=1048576"
      - "traefik.http.middlewares.authentik.forwardauth.address=http://authentik-server:9000/outpost.goauthentik.io/auth/traefik"
      - "traefik.http.middlewares.authentik.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.authentik.forwardauth.authResponseHeaders=Remote-User,X-Authentik-Username,X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version"
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 1.5G
        reservations:
          memory: 512M

  # --- AUTHENTIK WORKER ---
  authentik-worker:
    image: ghcr.io/goauthentik/server:2025.12.4
    container_name: authentik-worker
    user: "${PUID}:${PGID}"
    command: worker
    restart: unless-stopped
    depends_on:
      postgres-common:
        condition: service_healthy
    environment:
      - DOCKER_HOST=tcp://docker-proxy-read:2375
      - AUTHENTIK_POSTGRESQL__HOST=postgres-common
      - AUTHENTIK_POSTGRESQL__USER=${POSTGRES_USER}
      - AUTHENTIK_POSTGRESQL__NAME=authentik
      - AUTHENTIK_POSTGRESQL__PASSWORD=${POSTGRES_PASSWORD}
      - AUTHENTIK_ERROR_REPORTING__ENABLED=true
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY}
      - AUTHENTIK_EMAIL__HOST=${AUTHENTIK_EMAIL__HOST}
      - AUTHENTIK_EMAIL__PORT=${AUTHENTIK_EMAIL__PORT}
      - AUTHENTIK_EMAIL__USERNAME=${AUTHENTIK_EMAIL__USERNAME}
      - AUTHENTIK_EMAIL__PASSWORD=${AUTHENTIK_EMAIL__PASSWORD}
      - AUTHENTIK_EMAIL__USE_SSL=${AUTHENTIK_EMAIL__USE_SSL}
      - AUTHENTIK_EMAIL__FROM=${AUTHENTIK_EMAIL__FROM}
    volumes:
      - ${APPS_DATA_DIR}/authentik/certs:/certs
    networks:
      - lefrigo-net
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1G
        reservations:
          memory: 256M

  # --- TAILSCALE---
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    user: "0:0"
    hostname: ${TS_AUTHNAME}
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ${APPS_DATA_DIR}/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_STATEFUL_FILTERING=true
      - TS_ROUTES=192.168.1.0/24
      - TS_AUTHKEY=${TS_AUTHKEY}
    restart: unless-stopped
    networks:
      - lefrigo-net

networks:
  lefrigo-net:
    external: true